service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18000

[cn.Engine]
# only prefetch the matched db.table
prefetch-on-subscribed = [
    '^mo_catalog\.mo_tables$',
    '^mysql\..*$',
    '^test1\..*$',
    '^test2\.t1$',
]

[malloc]
check-fraction = 65536
enable-metrics = true

[observability]
disableMetric = false
enable-metric-to-prom = true
status-port = 7001
