service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32001",
]

[metacache]
memory-capacity = "512MB"

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"

[cn.Engine]
type = "distributed-tae"

[cn.txn]
enable-sacrificing-freshness = false
enable-cn-based-consistency = false
