service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[metacache]
memory-capacity = "512MB"

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8
disk-async-file-load = true

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
disableTrace = false
disableMetric = false

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"

[cn.Engine]
type = "distributed-tae"

[cn.txn]
