service-type = "DN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[metacache]
memory-capacity = "512MB"

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[dn]
uuid = "dd4dccb4-4d3c-41f8-b482-5251dc7a41bf"

[dn.Txn.Storage]
backend = "TAE"
log-backend = "logservice"

[dn.Txn]

[dn.Ckp]
flush-interval = "60s"
min-count = 100
scan-interval = "5s"
incremental-interval = "180s"
global-min-count = 60

[dn.LogtailServer]
listen-address = "0.0.0.0:32003"
service-address = "127.0.0.1:32003"
rpc-max-message-size = "16KiB"
rpc-payload-copy-buffer-size = "16KiB"
rpc-enable-checksum = true
logtail-collect-interval = "2ms"
logtail-response-send-timeout = "10s"
max-logtail-fetch-failure = 5
