service-type = "TN"
data-dir = "./etc/launch-minio-local/mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[[fileservice]]
backend = "DISK"
data-dir = "./etc/launch-minio-local/mo-data"
name = "LOCAL"

[[fileservice]]
backend = "MINIO"
name = "SHARED"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://127.0.0.1:9000"
key-prefix = "server/data"
key-id = "minio"
key-secret = "minio123"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "2GB"
disk-path = "etc/launch-minio-local/mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8

[[fileservice]]
backend = "MINIO"
name = "ETL"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://127.0.0.1:9000"
key-prefix = "server/etl"
key-id = "minio"
key-secret = "minio123"

[hakeeper-client]
service-addresses = ["127.0.0.1:32001"]

[tn]
uuid = "713F97B0-1E28-4F80-849D-FE0979AE734A"
port-base = 19000

[tn.Txn]

[tn.Txn.Storage]
backend = "TAE"
fileservice = "SHARED"
log-backend = "logservice"

[tn.Ckp]
flush-interval = "60s"
min-count = 100
scan-interval = "5s"
incremental-interval = "180s"
global-min-count = 60

[tn.LogtailServer]
rpc-max-message-size = "16KiB"
rpc-payload-copy-buffer-size = "16KiB"
rpc-enable-checksum = true
logtail-collect-interval = "2ms"
logtail-response-send-timeout = "10s"
max-logtail-fetch-failure = 10

[observability]
disableMetric = false
enable-metric-to-prom = true
status-port = 7001
