service-type = "CN"

[log]
level = "info"
format = "console"
max-size = 512

[[fileservice]]
backend = "DISK"
data-dir = "/var/lib/matrixone/data"
name = "LOCAL"

[[fileservice]]
backend = "MINIO"
name = "SHARED"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://minio:9000"
key-prefix = "server/data"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8

[[fileservice]]
backend = "MINIO"
name = "ETL"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://minio:9000"
key-prefix = "server/etl"

[hakeeper-client]
service-addresses = ["logservice:32001"]

#[observability]
#disableTrace = true
#disableMetric = true

[cn]
uuid = "dd1dccb3-4d3c-41f9-b482-5251dc7a41bf"
port-base = 18100
service-host = "cn-0"
sql-address = "cn-0:6001"

[cn.Engine]
type = "distributed-tae"

[cn.frontend]
port = 6001

[cn.txn]
