# service node type, [DN|CN|LOG]
service-type = "LOG"

[log]
level = "info"
format = "console"
max-size = 512

[[fileservice]]
backend = "DISK"
data-dir = "/var/lib/matrixone/data"
name = "LOCAL"

[[fileservice]]
backend = "MINIO"
name = "SHARED"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://minio:9000"
key-prefix = "server/data"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8

[[fileservice]]
backend = "MINIO"
name = "ETL"

[fileservice.s3]
bucket = "mo-test"
endpoint = "http://minio:9000"
key-prefix = "server/etl"

[observability]
statusPort = 7001
