logservices = [
    "./etc/launch-mem-engine/log.toml",
]

dnservices = [
    "./etc/launch-mem-engine/dn.toml"
]

cnservices = [
    "./etc/launch-mem-engine/cn.toml",
    "./etc/launch-mem-engine/cn2.toml",
]
