# service node type, [DN|CN|LOG]
service-type = "LOG"

[log]
level = "info"
format = "json"
max-size = 512

[logservice]
deployment-id = 1
data-dir = "node-3-data"
uuid = "9c4dccb4-4d3c-41f8-b482-5251dc7a41bf"
raft-address = "127.0.0.1:32020"
logservice-address = "127.0.0.1:32021"
gossip-address = "127.0.0.1:32022"
gossip-seed-addresses = [
  "127.0.0.1:32002",
]

[logservice.BootstrapConfig]
bootstrap-cluster = true
num-of-log-shards = 1
num-of-dn-shards = 1
num-of-log-shard-replicas = 1
init-hakeeper-members = [
  "131074:9c4dccb4-4d3c-41f8-b482-5251dc7a41bf",
]

[logservice.HAKeeperConfig]
tick-per-second = 1
log-store-timeout = "20s"
dn-store-timeout = "10s"

[[fileservice]]
name = "LOCAL"
backend = "MEM"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"
data-dir = "mo-data/local/etl"

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32021",
]

[observability]
statusPort = 7003
