# Log level: debug, info, warn, error, fatal.
level = "info"

# Log format, one of json or text.
format = "text"

# Enable automatic timestamps in log output, if not set, it will be defaulted to true.
# enable-timestamp = true

# Enable annotating logs with the full stack error message, if not set, it will be defaulted to false.
# enable-error-stack = false

# File logging.
[file]
# Log file name.
filename = "/tmp/db_log"

# Max log file size in MB (upper limit to 4096MB).
max-size = 300

# Max log file keep days. No clean up by default.
max-days = 0

# Maximum number of old log files to retain. No clean up by default.
max-backups = 0
