service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/s3"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"
disk-min-evict-interval = "7m"
disk-evict-target = 0.8

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = "dd1dccb5-4d3c-41f8-b482-5251dc7a41bf"
listen-address = "0.0.0.0:7002"
service-address = "127.0.0.1:7002"

[cn.Engine]
type = "distributed-tae"

[cn.frontend]
port = 16002
unix-socket = "/tmp/mysql2.sock"

[cn.lockservice]
listen-address = "0.0.0.0:7003"
service-address = "127.0.0.1:7003"

[cn.ctl.address]
listen-address = "0.0.0.0:9958"
service-address = "127.0.0.1:9958"

[cn.query-service.address]
listen-address = "0.0.0.0:29998"
service-address = "127.0.0.1:29998"

[cn.txn]
# mode = "Pessimistic"
