service-type = "CN"
data-dir = "./mo-data"

[log]
level = "error"
format = "json"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = "cn1"

[cn.Engine]
type = "distributed-tae"
