service-type = "DN"
data-dir = "./mo-data"

[log]
level = "error"
format = "json"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[dn]
uuid = "dn1"

[dn.Txn.Storage]
backend = "TAE"
log-backend = "logservice"

[dn.Ckp]
scanner-interval = "2s"
execution-levels = 2
execution-interval = "3s"
catalog-ckp-interval = "3s"
catalog-unckp-limit = 2
flush-interval = "6s"
