# service node type, [DN|CN|LOG]
service-type = "CN"

[log]
level = "error"
format = "console"
max-size = 512

[hakeeper-client]
service-addresses = [
    "1",
    "2"
]

[[fileservice]]
name = "LOCAL"
backend = "MEM"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"
data-dir = "store"

[cn]
uuid = "cn1"

[cn.Engine]
type = "tae"

# you can move your vars in system_vars_config.toml to here. empty for default value
# log vars in system_vars_config.toml was removed. use [log] to set log vars
[cn.frontend]

[observability]
disableTrace = true
disableMetric = true
