# service node type, [DN|CN|LOG]
service-type = "CN"

[log]
level = "debug"
format = "json"
max-size = 512

[hakeeper-client]
service-addresses = [
    "1",
    "2"
]

[clock]
# Due to the poor performance of ci machines, which can cause timers that detect clock 
# drift to be delayed in scheduling execution, the configuration is larger.
max-clock-offset = "1s"

[[fileservice]]
name = "LOCAL"
backend = "MEM"

[[fileservice]]
name = "S3"
backend = "MEM"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"
data-dir = "store"

[cn]
uuid = "cn1"

[cn.Engine]
type = "tae"

# you can move your vars in system_vars_config.toml to here. empty for default value
# log vars in system_vars_config.toml was removed. use [log] to set log vars
[cn.frontend]

