service-type = "STANDALONE"

[log]
level = "debug"
format = "json"
max-size = 512

[hakeeper-client]
service-addresses = [
  "127.0.0.1:32000",
]

[cn]
uuid = "cn1"

[cn.Engine]
type = "distributed-tae"

[dn]
uuid = "42"

[dn.Txn.Storage]
backend = "TAE"

[logservice]
deployment-id = 1
uuid = "9c4dccb4-4d3c-41f8-b482-5251dc7a41bf"
gossip-seed-addresses = [
  "127.0.0.1:32002",
]
data-dir = "store/logservice"

[logservice.BootstrapConfig]
bootstrap-cluster = true
num-of-log-shards = 1
num-of-dn-shards = 1
num-of-log-shard-replicas = 1
init-hakeeper-members = [
  "131072:9c4dccb4-4d3c-41f8-b482-5251dc7a41bf",
]

[[fileservice]]
name = "LOCAL"
backend = "MEM"

[[fileservice]]
name = "SHARED"
backend = "MEM"

[[fileservice]]
name = "PUBLIC"
backend = "DISK-RAW"
data-dir = "store"

