service-type = "CN"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512
filename = "/logs/cn1.log"

[hakeeper-client]
service-addresses = [
  "mo-log:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/shared"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[observability]
disableTrace = true
disableMetric = true

[cn]
uuid = "dd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
port-base = 18100
listen-address = "0.0.0.0:18101"
service-address = "mo-cn1:18101"
service-host = "mo-cn1"
sql-address = "mo-cn1:16001"

[cn.Engine]
type = "distributed-tae"

[cn.frontend]
port = 16001
host = "0.0.0.0"
proxy-enabled = true