service-type = "PROXY"
data-dir = "./mo-data"

[log]
level = "info"
format = "console"
max-size = 512
filename = "/logs/proxy.log"

[hakeeper-client]
service-addresses = [
  "mo-log:32001",
]

[[fileservice]]
name = "LOCAL"
backend = "DISK"

[[fileservice]]
name = "SHARED"
backend = "DISK"
data-dir = "mo-data/shared"

[fileservice.cache]
memory-capacity = "512MB"
disk-capacity = "8GB"
disk-path = "mo-data/file-service-cache"

[[fileservice]]
name = "ETL"
backend = "DISK-ETL"

[proxy]
uuid = "rd1dccb4-4d3c-41f8-b482-5251dc7a41bf"
listen-address = "0.0.0.0:6009"

[proxy.cluster]
refresh-interval = "5s"