on:
  push:
    branches:
      - main

jobs:
  contribu-readme-job:
    runs-on: ubuntu-latest
    name: Contributor list
    steps:
      - name: First Contribution Check
        id: first-check
        uses: sukki37/first-contribution-check-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        if: ${{ steps.first-check.outputs.isNewContributor == 'true' }}
        with:
          image_size: 30
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTION }}