name: Test Distributed Verison Matrixone

on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - main
    
jobs: 
  distributed-tests:
    runs-on: ubuntu-latest
    name: Matrixone distributed testing
    timeout-minutes: 30

    steps:
      - name: Chekcout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build MO image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: optools/test/Dockerfile.mo
          push: false
          load: true
          tags: matrixorigin/matrixone:dt
          builder: ${{ steps.buildx.outputs.name }}
        
      - name: Build BVT image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: optools/test/Dockerfile.bvt
          push: false
          load: true
          tags: matrixorigin/mysql-tester:dt
          builder: ${{ steps.buildx.outputs.name }}

      - name: Build the docker-compose stack
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: docker-compose -f ./optools/test/docker-compose.yaml up -d --no-build

      - name: Check running containers
        run: docker ps -a

      - name: Check container network
        run:  docker network list
  
      - name: Run test suite
        run: docker run --tty --rm --name mysql-tester --network test_monet matrixorigin/mysql-tester:dt -host 172.19.0.2 -port 6001 -user dump -passwd 111

      - name: Move cache
        if:  ${{ always() }}
        run: |
          docker-compose -f ./optools/test/docker-compose.yaml down --remove-orphans

      - name: Step to run on filure or cancelled    
        if : ${{ failure() || cancelled() }}
        uses: actions/upload-artifact@v2
        with:
          name: distributed-tests-log
          path: log/
