
name: PR Document Issue Check
on:
  pull_request_target:
    types: [ opened ]
    branches: [ main,'[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  ducu_issue_check:
    runs-on: ubuntu-latest
    steps:
      - uses: guguducken/pull-issue-reviewer@v0.1.0
        with:
          token_action: ${{ secrets.TOKEN_ACTION }}
          uri_notice: ${{ secrets. WECHAT_WORK_BOT_WEBHOOK }}
          id_label: "5138861359"
          reviewers: "lacrimosaprinz,dengn"
          mentions: "Prinz,DengNan"
      
