name: auto add issue to project

on:
  issues:
    types:
      - opened
      - labeled
      - transferred

jobs:
  auto-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Add Issue To GitHub Project
        uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/matrixorigin/projects/13/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: kind/bug,kind/docs,kind/enhancement,kind/feature,kind/questions,kind/performance,kind/refactoring
          label-operator: OR
