name:  MO Checkin Regression On EKS

on:
  pull_request_target:
    types:
      - closed
env: 
   branch: main

jobs:
  docker_image_build:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: arm64-runner 
    timeout-minutes: 60
    name: BUILD MO DOCKER IMAGE
    outputs:
       version: ${{ steps.prep.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/matrixone
          ref: ${{ env.branch }}
          path: ./matrixone

      - name: Prepare And Build
        id: prep
        run: |
          cd $GITHUB_WORKSPACE/matrixone
          LAST_COMMIT_ID=$(git rev-parse --short HEAD)
          DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/matrixone
          VERSION=commit-$LAST_COMMIT_ID

          TAGS="${DOCKER_IMAGE}:${VERSION}"


          # Set output parameters.
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
          echo ${TAGS}
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          docker build -t $TAGS -f optools/images/Dockerfile .

          docker push $TAGS

  setup_mo_test_env:
    if: ${{ needs.docker_image_build.result == 'success' && github.event.pull_request.merged == true }}
    needs: docker_image_build
    runs-on: arm64-runner
    timeout-minutes: 60
    name: SETUP MO TEST ENV
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/matrixone
          ref: ${{ env.branch }}
          path: ./matrixone

      - name: Prepare Test EVN
        run: |
          sudo apt-get update
          sudo apt-get install git vim net-tools mysql-client openjdk-8-jdk sysbench bc pip -y
          sudo pip3 install PyYAML==6.0
          sudo pip3 install shyaml==0.6.2
          
          
      - name: Prepare AWS Tools
        run: |
          sudo apt-get update && sudo apt-get install awscli -y
          sudo apt-get install -y ca-certificates curl
      - name: Prepare AWS Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'
        id: install
                   
      - name: Prepare AWS Config
        run: |
           aws configure<<EOF
           ${{ secrets.AWS_ACCESSKEY_ID }}
           ${{ secrets.AWS_SECRETACCESS_KEY }}
           us-west-2
           json
           exit
           EOF
           
      - name: Prepare Kubeconfig
        run: |
           aws eks --region us-west-2 update-kubeconfig --name eks-ci --kubeconfig eks-ci
           export KUBECONFIG=$(pwd)/eks-ci
           if [ "$(kubectl get namespaces| grep mo-big-data-${{ github.event.pull_request.number }} |wc -l)" -eq 0 ];then export KUBECONFIG=$(pwd)/eks-ci; kubectl create namespace mo-big-data-${{ github.event.pull_request.number }} ;kubectl -n mo-big-data-${{ github.event.pull_request.number }} create secret generic aws-secret --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESSKEY_ID }} --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRETACCESS_KEY }};fi 
       
      - name: ECHO mo-big-data.yaml
        run: |
          echo '${{ needs.docker_image_build.outputs.version }}'

          cd $GITHUB_WORKSPACE/matrixone
          sed -i 's/nsformobigtest/mo-big-data-${{ github.event.pull_request.number }}/g' $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml
          sed -i 's/s3pathformobigtest/mo-big-data\/${{ github.event.pull_request.number }}/g' $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml
          sed -i "s/imagetag/${{ needs.docker_image_build.outputs.version }}/g" $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml
          cat $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml

      - name: Clean EKS ENV
        run: |
          export KUBECONFIG=$(pwd)/eks-ci
          if [ "$(kubectl -n mo-big-data-${{ github.event.pull_request.number }} get pod|grep "mo-big-data-*"|wc -l)" -ne 0 ];then export KUBECONFIG=$(pwd)/eks-ci; kubectl -n mo-big-data-${{ github.event.pull_request.number }} delete -f $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml;sleep 30s;fi
          kubectl get bucket -n mo-big-data-${{ github.event.pull_request.number }} | grep bucket | awk '{system("kubectl delete bucket/"$1" -n mo-big-data-${{ github.event.pull_request.number }}")}'
          aws s3 rm s3://mo-big-data/${{ github.event.pull_request.number }} --recursive > /dev/null 2>&1
          
          
      - name: Create MO Cluster
        run: |
          export KUBECONFIG=$(pwd)/eks-ci
          kubectl -n mo-big-data-${{ github.event.pull_request.number }} apply -f $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml
          sleep 100s
          while true; do if [ "$(kubectl -n mo-big-data-${{ github.event.pull_request.number }} get pods --field-selector status.phase=Running|grep "mo-big-data-*"|wc -l)" -eq 6 ]; then break; else sleep 10s; continue; fi; done
          kubectl -n mo-big-data-${{ github.event.pull_request.number }} get pod
          if [ ! -d $GITHUB_WORKSPACE/mo-server-log ]; then mkdir $GITHUB_WORKSPACE/mo-server-log;fi;


  test:
    if: ${{ needs.setup_mo_test_env.result == 'success' && github.event.pull_request.merged == true }}  #
    name: MO BIG DATA TOTAL TEST
    runs-on: arm64-runner
    timeout-minutes: 120
    needs: [setup_mo_test_env,docker_image_build]
    steps:
      - name: Clone mo-load-data Repo
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/mo-load-data
          token: ${{secrets.TOKEN_ACTION}}
          path: ./mo-load-data
          ref: main

      - name: Clone mo-ssb Repo
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/mo-ssb
          token: ${{secrets.TOKEN_ACTION}}
          path: ./mo-ssb
          ref: main
          
      - name: Clone mo-tpch Repo
        if: ${{ always() && !cancelled() }}
        uses: actions/checkout@v2
        with:
          repository: matrixorigin/mo-tpch
          token: ${{secrets.TOKEN_ACTION}}
          path: ./mo-tpch
          ref: main

      - name: Clone mo-load Repo
        if: ${{ always() && !cancelled() }}
        uses: actions/checkout@v2
        with:
          repository: matrixorigin/mo-load
          token: ${{secrets.TOKEN_ACTION}}
          path: ./mo-load
          ref: main

      - name: Clone mo-sysbench Repo
        if: ${{ always() && !cancelled() }}
        uses: actions/checkout@v2
        with:
          repository: matrixorigin/mo-sysbench
          token: ${{secrets.TOKEN_ACTION}}
          path: ./mo-sysbench
          ref: main

      - name: Clone mo-tpcc Repo
        if: ${{ always() && !cancelled() }}
        uses: actions/checkout@v2
        with:
          repository: matrixorigin/mo-tpcc
          token: ${{secrets.TOKEN_ACTION}}
          path: ./mo-tpcc
          ref: main
          
      - name: Prepare Test EVN
        run: |
          sudo apt-get update
          sudo apt-get install git vim net-tools mysql-client openjdk-8-jdk sysbench bc pip -y
          sudo pip3 install PyYAML==6.0
          sudo pip3 install shyaml==0.6.2
          sudo pip3 install PyMySQL==1.0.2

      - name: Prepare AWS Tools
        run: |
          sudo apt-get update && sudo apt-get install awscli -y 
          sudo apt-get install -y ca-certificates curl

      - name: Prepare AWS Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'
        id: install

      - name: Prepare AWS Config
        run: |
           aws configure<<EOF
           ${{ secrets.AWS_ACCESSKEY_ID }}
           ${{ secrets.AWS_SECRETACCESS_KEY }}
           us-west-2
           json
           exit
           EOF
      
      - name: Prepare Kubeconfig
        run: |
           aws eks --region us-west-2 update-kubeconfig --name eks-ci --kubeconfig eks-ci
           export KUBECONFIG=$(pwd)/eks-ci
           if [ "$(kubectl get namespaces|grep mo-big-data-${{ github.event.pull_request.number }} |wc -l)" -eq 0 ];then export KUBECONFIG=$(pwd)/eks-ci; kubectl create namespace mo-big-data-${{ github.event.pull_request.number }};kubectl -n mo-big-data-${{ github.event.pull_request.number }} create secret generic aws-secret --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESSKEY_ID }} --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRETACCESS_KEY }};fi 
      
      - name: Get MO Cluster Addr
        id: get_mo_addr
        run: |
          export KUBECONFIG=$(pwd)/eks-ci
          mo_svc_ip=$(kubectl -n mo-big-data-${{ github.event.pull_request.number }} get svc | grep "6001/TCP"|awk '{print $3}')
          echo $mo_svc_ip
          echo "mo_svc_ip=${mo_svc_ip}" >> $GITHUB_OUTPUT
          
      - name: Start Load SSB 10G Data And Test
        if: ${{ always() }}
        timeout-minutes: 10
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          cd $GITHUB_WORKSPACE/mo-load-data
          ./load.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -c cases/00_from_s3/ssb_10 -r -m -g
          # start test
          cd $GITHUB_WORKSPACE/mo-ssb
          ./run.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -q all -s 10 -t 5

      # start tpch test
      - name: Load TPCH 10G Test Data
        if: ${{ always() }}
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          cd $GITHUB_WORKSPACE/mo-load-data
          ./load.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -c cases/00_from_s3/tpch_10 -r -m -g

      - name: Start TPCH 10G Test
        if: ${{ always() }}
        timeout-minutes: 10
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          cd $GITHUB_WORKSPACE/mo-tpch
          ./run.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -q all -s 10 -t 5

      # start sysbench test
      - name: Start OLTP Insert Test With 100 Threads
        if: ${{ always() }}
        timeout-minutes: 15
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s

          cd $GITHUB_WORKSPACE/mo-load
          sed -i 's/127.0.0.1/${{ steps.get_mo_addr.outputs.mo_svc_ip }}/g' mo.yml
          
          echo 'Start Prepare Data of 10-tables-100000-per-table'
          ./start.sh -m SYSBENCH -n 10 -s 100000
          sleep 10
          
          echo ''
          echo 'Start OLTP Insert Test With 100 threads'
          ./start.sh -c cases/sysbench/simple_insert_10_100000 -t 100 -g

      - name: Start OLTP Delete Test With 100 Threads
        if: ${{ always() }}
        timeout-minutes: 15
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          
          cd $GITHUB_WORKSPACE/mo-load
          echo 'Start Prepare Data of 10-tables-100000-per-table'
          ./start.sh -m SYSBENCH -n 10 -s 100000
          sleep 10
          
          echo ''
          echo 'Start OLTP Delete Test With 100 threads'
          ./start.sh -c cases/sysbench/delete_pk_10_100000 -t 100 -g
          
      - name: Start OLTP Update Test With 100 Threads
        if: ${{ always() }}
        timeout-minutes: 15
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          
          cd $GITHUB_WORKSPACE/mo-load
          echo 'Start Prepare Data of 10-tables-100000-per-table'
          ./start.sh -m SYSBENCH -n 10 -s 100000
          sleep 10
          
          echo ''
          echo 'Start OLTP UPDATE Test With 100 threads'
          ./start.sh -c cases/sysbench/update_pk_10_100000 -t 100 -g

      - name: Start OLTP Point Select Test With 100 Threads
        if: ${{ always() }}
        timeout-minutes: 15
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          
          cd $GITHUB_WORKSPACE/mo-load
          echo 'Start Prepare Data of 10-tables-100000-per-table'
          ./start.sh -m SYSBENCH -n 10 -s 100000
          sleep 10
          
          echo ''
          echo 'Start OLTP Point Select Test With 100 threads'
          ./start.sh -c cases/sysbench/point_select_10_100000 -t 100 -g
     
     # start tpcc test
      - name: Load TPCC 10 Warehouse Data
        if: ${{ always() }}
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          cd $GITHUB_WORKSPACE/mo-load-data
          ./load.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -c cases/00_from_s3/tpcc_10 -r -m -g 

      - name: Start TPCC 10 Warehouses 10 terminals Test
        if: ${{ always() }}
        timeout-minutes: 15
        run: |
          export LC_ALL="C.UTF-8"
          locale
          sleep 60s
          
          cd $GITHUB_WORKSPACE/mo-tpcc
          cp props.mo props_10.mo
          sed -i '/.*terminals=*/c\terminals=10' props_10.mo
          sed -i '/.*warehouses=*/c\warehouses=10' props_10.mo
          sed -i 's/tpcc/tpcc_10/g' props_10.mo
          sed -i 's/127.0.0.1/${{ steps.get_mo_addr.outputs.mo_svc_ip }}/g' props_10.mo
          sed -i '/runMins=*/c\runMins=10' props_10.mo
          sed -i '/.*expectedErrorCodes=*/c\expectedErrorCodes=20619,1062' props_10.mo
          ./runBenchmark.sh props_10.mo
          ./runVerify.sh props_10.mo
          
          if [ -f benchmarksql-error.log ];then
            mv benchmarksql-error.log benchmarksql-error-10-10.log
          fi
      
      # start large table test
      # TODO(sudong)
      # - name: Load TPCH 10G Test Data
      #   if: ${{ always() && !cancelled() }}
      #   run: |
      #     export LC_ALL="C.UTF-8"
      #     locale
      #     sleep 50s
      #     cd $GITHUB_WORKSPACE/mo-load-data
      #     ./load.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -c cases/00_from_s3/tpch_10 -r -m -g

      # - name: Start Large Table Update And Delete
      #   if: ${{ always() && !cancelled() }}
      #   timeout-minutes: 1
      #   run: |
      #     # export LC_ALL="C.UTF-8"
      #     # cd $GITHUB_WORKSPACE/mo-tpch
      #     # ./run.sh -h ${{ steps.get_mo_addr.outputs.mo_svc_ip }} -q all -s 10 -t 5
      - name : ISSUE Notice
        if: ${{ failure() || cancelled() }}
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}
        with:
          msgtype: markdown
          content: "MO Checkin Regression On EKS failed: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\nCreator:<font color=\"warning\">${{ github.event.pull_request.user.login }}</font>\nAction Link: [Link](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})  <@shuqi.qin><@JiejieJia><@SuDong>"


  clean_up_env:
    if: ${{ always() && !cancelled() && needs.setup_mo_test_env.result == 'success' && github.event.pull_request.merged == true }} #
    name: CLEAN UP ENV
    runs-on: arm64-runner
    needs: [docker_image_build,setup_mo_test_env,test]
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: matrixorigin/matrixone
          ref: ${{ env.branch }}
          path: ./matrixone

      - name: Prepare AWS Tools
        run: |
          sudo apt-get update && sudo apt-get install awscli -y 
          sudo apt-get install -y ca-certificates curl
      - name: Prepare AWS Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'
        id: install

      - name: Prepare AWS Config
        run: |
           aws configure<<EOF
           ${{ secrets.AWS_ACCESSKEY_ID }}
           ${{ secrets.AWS_SECRETACCESS_KEY }}
           us-west-2
           json
           exit
           EOF
      - name: Prepare Kubeconfig
        run: |
           aws eks --region us-west-2 update-kubeconfig --name eks-ci --kubeconfig eks-ci
           export KUBECONFIG=$(pwd)/eks-ci
           if [ "$(kubectl get namespaces|grep mo-big-data-${{ github.event.pull_request.number }} |wc -l)" -eq 0 ];then export KUBECONFIG=$(pwd)/eks-ci; kubectl create namespace mo-big-data-${{ github.event.pull_request.number }} ;kubectl -n mo-big-data-${{ github.event.pull_request.number }} create secret generic aws-secret --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESSKEY_ID }} --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRETACCESS_KEY }};fi 

      - name: Check MO Status and Clean ENV
        if: ${{ always() && !cancelled() }}
        run: |
          cd $GITHUB_WORKSPACE/matrixone
          sed -i 's/nsformobigtest/mo-big-data-${{ github.event.pull_request.number }}/g' $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml
          sed -i 's/s3pathformobigtest/mo-big-data\/${{ github.event.pull_request.number }}/g' $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml

          #delete matrixone cluster
          cd $GITHUB_WORKSPACE
          export KUBECONFIG=$(pwd)/eks-ci
          kubectl -n mo-big-data-${{ github.event.pull_request.number }} get pod
          kubectl -n mo-big-data-${{ github.event.pull_request.number }} delete -f $GITHUB_WORKSPACE/matrixone/optools/big_data_eks/mo_big_data.yaml
          sleep 60
          kubectl -n mo-big-data-${{ github.event.pull_request.number }} get pod


          # move result to s3://mo-big-data/result/
          aws s3 rm s3://mo-big-data/result/${{ github.event.pull_request.number }} --recursive > /dev/null 2>&1
          aws s3 mv s3://mo-big-data/${{ github.event.pull_request.number }}/etl s3://mo-big-data/result/${{ github.event.pull_request.number }}/etl --recursive > /dev/null 2>&1
          kubectl get bucket -n mo-big-data-${{ github.event.pull_request.number }} | grep bucket | awk '{system("kubectl delete bucket/"$1" -n mo-big-data-${{ github.event.pull_request.number }}")}'

          kubectl delete namespace mo-big-data-${{ github.event.pull_request.number }}
