# Define workflow name.
# This workflow is used to run with specific branch of bvt,
# pls make sure that the name pr is equals to the target branch's name.
name: Run Selected BVT

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch.
  pull_request:
    types: [ labeled, synchronize, reopened, edited ]
    branches: main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'good first issue')
    runs-on: ubuntu-latest
    name: Build on CentOS/x64

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it.
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build Configure
        run: |
          cd $GITHUB_WORKSPACE && make clean && make config

      - name: Build Binary
        run: |
          make build

      - name: Build Verification Testing
        run: |
          export branch=$(echo "${{ github.event.pull_request.title }}" | awk -F " " '{print $NF}')
          make bvt BVT_BRANCH="$branch"

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: gfi_test_reports
          path: |
            ${{ github.workspace }}/coverage.html
          retention-days: 7
